stages:
  - build
  - deploy

docker-build:
  image: docker-proxy.fit-haui.edu.vn/docker:20.10.16
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_HOST: tcp://docker:2376
  services:
    - name: docker:20.10.16-dind
  before_script:
    - |
      for i in $(seq 1 30)
      do
          docker info && break
          echo "Waiting for docker to start"
          sleep 1s
      done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://nexus.fit-haui.edu.vn/repository/docker-hosted/
  script:
    - docker build -t nexus.fit-haui.edu.vn/nodejs-image:latest .
    - docker push nexus.fit-haui.edu.vn/nodejs-image:latest
  only:
    - main

deploy:
  image:
    name: docker-proxy.fit-haui.edu.vn/bitnami/kubectl:1.23
    entrypoint: ['']
  stage: deploy
  script:
    - kubectl config get-contexts
    - kubectl config use-context sample-group/kubernetes-agent:sample-group-agent
    - kubectl rollout restart deployment nodejs-deployment
  only:
    - main
