version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    docker:
      - image: node:lts-alpine
        auth:
          username: cocvu99
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    docker:
      - image: node:lts-alpine
        auth:
          username: cocvu99
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run: echo "this is the TEST NE!!!!"